-- Crear la tabla OWNER
CREATE TABLE OWNER (
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME
);

-- Crear la tabla PET
CREATE TABLE PET (
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    OWNER_ID VARCHAR(36),
    NAME VARCHAR(255) NOT NULL,
    TYPE VARCHAR(255) NOT NULL,
    BREED VARCHAR(255),
    DATE_BIRTH DATE NOT NULL,
    CHIP VARCHAR(255) UNIQUE,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME,
    IMAGE_URL VARCHAR(255),
    DISABLE_DATE DATE,
    FOREIGN KEY (OWNER_ID) REFERENCES OWNER(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Crear la tabla MEDICINE
CREATE TABLE MEDICINE (
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    PET_ID VARCHAR(36),
    NAME VARCHAR(255) NOT NULL,
    DOSE VARCHAR(255) NOT NULL,
    FREQUENCY VARCHAR(255) NOT NULL,
    ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    START_DATE DATE,
    END_DATE DATE,
    FOREIGN KEY (PET_ID) REFERENCES PET(ID) ON DELETE SET NULL ON UPDATE CASCADE
);

-- Crear la tabla VISIT
CREATE TABLE VISIT (
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    PET_ID VARCHAR(36),
    DESCRIPTION TEXT,
    DATE_VISIT DATE NOT NULL,
    FILE VARCHAR(255),
    FOREIGN KEY (PET_ID) REFERENCES PET(ID) ON DELETE CASCADE ON UPDATE CASCADE
);